"""feed table: the feed list becomes rows

Creates the table and **seeds the twelve feeds that were in
`config/sources.yml`**, each with the probe result that earned it its place. The
notes are carried across verbatim: they were comments above each YAML entry, and
a migration that created an empty table would have thrown that evidence away at
the first `git rm` while looking like a clean move.

Seeded here rather than in `seed_page.py` because these rows are a *migration of
existing configuration*, not a fresh install. Running the seed script against a
database that already has feeds should not resurrect a feed the operator
deleted, which is exactly what a re-runnable seeder would do.

Idempotent: the insert skips any (page, url) already present, so a re-run adds
nothing. Pages are matched by name — unique, and the only stable handle a YAML
file had.

Revision ID: 103581b4d2f1
Revises: 148cf3f13e08
Create Date: 2026-08-10 18:34:07.556061

"""
from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa

# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '103581b4d2f1'
down_revision: Union[str, Sequence[str], None] = '148cf3f13e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'url', name='uq_feed_page_url')
    )
    op.create_index(op.f('ix_feed_page_id'), 'feed', ['page_id'], unique=False)
    # ### end Alembic commands ###

    _seed()


# The feed list as `config/sources.yml` carried it, probed 2026-07-31 (history)
# and 2026-08-09 (news). The feeds that were probed and *rejected* stayed in
# sources.yml as a comment — a row can only record a feed that exists, and the
# rejections are the other half of the same evidence.
SEED: dict[str, list[tuple[str, str, str | None]]] = {
    "History Retraced": [
        (
            "Smithsonian Magazine",
            "https://www.smithsonianmag.com/rss/history/",
            "31 items, 179-char summaries, every item imaged.",
        ),
        (
            "Live Science",
            "https://www.livescience.com/feeds/tag/archaeology",
            "50 items, every item imaged. The archaeology tag, not /all.",
        ),
        (
            "Science Daily",
            "https://www.sciencedaily.com/rss/fossils_ruins/archaeology.xml",
            "Longest summaries here at 357 chars, but carries no images at all.",
        ),
        (
            "Atlas Obscura",
            "https://www.atlasobscura.com/feeds/latest",
            "1882-char bodies — by a wide margin the richest source in this list.",
        ),
        (
            "The History Blog",
            "http://www.thehistoryblog.com/feed",
            "Only 5 items, but 420-char summaries and unmixed history.",
        ),
        ("HistoryExtra", "https://www.historyextra.com/feed/", None),
        (
            "All That's Interesting",
            "https://allthatsinteresting.com/feed",
            "Highest volume of the keepers at 100 items.",
        ),
    ],
    "The Fact Feed": [
        (
            "Axios",
            "https://api.axios.com/feed/",
            "100 items and 3356-char bodies — by a wide margin the richest source "
            "in either list. It surfaces rarely (1-2 of 50) because it publishes "
            "in bursts rather than continuously, and is kept for what it carries "
            "when it does.",
        ),
        (
            "The Guardian",
            "https://www.theguardian.com/world/rss",
            "45 items, 552-char summaries, every item imaged. The spine of the grid.",
        ),
        (
            "BBC News",
            "https://feeds.bbci.co.uk/news/world/rss.xml",
            "Thin at 114 chars, but the freshest of all of them and every item "
            "imaged — it is what puts a breaking story on the grid first.",
        ),
        (
            "France 24",
            "https://www.france24.com/en/rss",
            "382-char summaries, fully imaged, and not an Anglosphere desk — it "
            "carries stories the other four do not run.",
        ),
        (
            "The Hill",
            "https://thehill.com/news/feed/",
            "Only 15 items, but 357-char summaries and the US politics beat this "
            "page actually posts — the midterm-money and Senate-vote lane.",
        ),
    ],
}


def _seed() -> None:
    connection = op.get_bind()
    now = datetime.now(timezone.utc)

    for page_name, feeds in SEED.items():
        page_id = connection.execute(
            sa.text("SELECT id FROM page WHERE name = :name"), {"name": page_name}
        ).scalar()
        if page_id is None:
            # A database seeded with different Pages is not a broken migration.
            # The table is what this revision is for; the rows are a convenience
            # for the two Pages that had a YAML entry.
            continue

        for name, url, note in feeds:
            already = connection.execute(
                sa.text("SELECT 1 FROM feed WHERE page_id = :page_id AND url = :url"),
                {"page_id": page_id, "url": url},
            ).scalar()
            if already:
                continue
            connection.execute(
                sa.text(
                    "INSERT INTO feed (page_id, name, url, note, created_at) "
                    "VALUES (:page_id, :name, :url, :note, :created_at)"
                ),
                {
                    "page_id": page_id,
                    "name": name,
                    "url": url,
                    "note": note,
                    "created_at": now,
                },
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_page_id'), table_name='feed')
    op.drop_table('feed')
    # ### end Alembic commands ###
