"""baseline: page, source_item, draft

The schema as it stood when Alembic was adopted, the day after the move to
Supabase. It was never *run* against the live database — those tables were built
by `create_all` and the database was `alembic stamp`ed at this revision. It
exists so a fresh database can be built from migrations alone, and so the next
change has something to be a diff against.

Autogenerated against a throwaway SQLite file, because autogenerate diffs the
models against whatever it is pointed at and Supabase already matched.

Note the enum columns: `native_enum=False, length=32`, not a Postgres `CREATE
TYPE`. That is `models._stored_enum` and it stays that way with Alembic in place
— a native enum would make every new member an `ALTER TYPE` migration, and would
build a schema the SQLite test fixture cannot express.

Revision ID: 148cf3f13e08
Revises:
Create Date: 2026-08-10 13:09:45.248820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '148cf3f13e08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facebook_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metricool_blog_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('watermark_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_facebook_page_id'), 'page', ['facebook_page_id'], unique=True)
    op.create_index(op.f('ix_page_name'), 'page', ['name'], unique=True)
    op.create_table('source_item',
    sa.Column('kind', sa.Enum('competitor_post', 'tweet', 'rss', name='sourcekind', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_for_page_id', sa.Integer(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['synced_for_page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'external_id', name='uq_source_item_kind_external')
    )
    op.create_index(op.f('ix_source_item_kind'), 'source_item', ['kind'], unique=False)
    op.create_index(op.f('ix_source_item_synced_for_page_id'), 'source_item', ['synced_for_page_id'], unique=False)
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('generating', 'review', 'approved', 'rejected', 'failed', name='draftstatus', native_enum=False, length=32), nullable=False),
    sa.Column('hook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('highlight_phrases', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('image_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hero_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composed_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inset_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inset_size_px', sa.Integer(), nullable=True),
    sa.Column('inset_x_ratio', sa.Float(), nullable=True),
    sa.Column('inset_y_ratio', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('metricool_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_metricool_post_id'), 'draft', ['metricool_post_id'], unique=False)
    op.create_index(op.f('ix_draft_page_id'), 'draft', ['page_id'], unique=False)
    op.create_index(op.f('ix_draft_source_item_id'), 'draft', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_draft_status'), 'draft', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_status'), table_name='draft')
    op.drop_index(op.f('ix_draft_source_item_id'), table_name='draft')
    op.drop_index(op.f('ix_draft_page_id'), table_name='draft')
    op.drop_index(op.f('ix_draft_metricool_post_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_source_item_synced_for_page_id'), table_name='source_item')
    op.drop_index(op.f('ix_source_item_kind'), table_name='source_item')
    op.drop_table('source_item')
    op.drop_index(op.f('ix_page_name'), table_name='page')
    op.drop_index(op.f('ix_page_facebook_page_id'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
