"""draft hero_from_source: the feed's own picture as the hero

Revision ID: 20974f89ec28
Revises: 3749e016826e
Create Date: 2026-08-11 20:57:55.132473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20974f89ec28'
down_revision: Union[str, Sequence[str], None] = '3749e016826e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adjusted from what autogenerate wrote, which was the bare

        op.add_column('draft', sa.Column(..., sa.Boolean(), nullable=False))

    and would have failed outright: Postgres cannot add a NOT NULL column with
    no default to a table that already has rows, and `draft` has seventeen. The
    error is at deploy time, on the one command a deploy cannot skip.

    So the column arrives with a server default, which backfills every existing
    row to `false` — the right answer, since every draft that already exists was
    drawn by the model rather than from a feed.

    The default is then **dropped**. It exists only to make the backfill legal;
    leaving it in place would put the default in two places, and the day the
    Python default changes the database would quietly disagree with it.
    """
    op.add_column(
        "draft",
        sa.Column(
            "hero_from_source",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("draft", "hero_from_source", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'hero_from_source')
    # ### end Alembic commands ###
