"""the second card template, and its headline badge

Revision ID: 24109305dae9
Revises: beada1f913db
Create Date: 2026-08-11 04:04:32.827341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24109305dae9'
down_revision: Union[str, Sequence[str], None] = 'beada1f913db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('badge_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('page_layout', sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('page_layout', sa.Column('badge_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('page_layout', sa.Column('badge_font_size_px', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_layout', 'badge_font_size_px')
    op.drop_column('page_layout', 'badge_color')
    op.drop_column('page_layout', 'template')
    op.drop_column('page', 'badge_text')
    # ### end Alembic commands ###
