"""page.avatar_url: the brand logo Metricool serves

Revision ID: 2b969a594ed6
Revises: 3a5c60b49f2f
Create Date: 2026-08-10 22:46:44.737052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b969a594ed6'
down_revision: Union[str, Sequence[str], None] = '3a5c60b49f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'avatar_url')
    # ### end Alembic commands ###
