"""draft inset ring: per-draft border width and colour

Both nullable, and null is load-bearing rather than "not filled in": it means
the draft takes the Page's `page_layout.portrait_*`, which is the same contract
`inset_size_px` beside them already has. So there is no backfill and no server
default — every existing row keeps rendering exactly as it does today, because
null is what it already resolves through.

Nullable also makes this safe to apply before the code that reads it: the
columns are simply unread until then.

Revision ID: 3749e016826e
Revises: 5cac274859ce
Create Date: 2026-08-11 15:42:26.798782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3749e016826e'
down_revision: Union[str, Sequence[str], None] = '5cac274859ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('inset_border_width_px', sa.Integer(), nullable=True))
    op.add_column('draft', sa.Column('inset_border_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'inset_border_color')
    op.drop_column('draft', 'inset_border_width_px')
    # ### end Alembic commands ###
