"""page_layout: per-Page overrides to the composed image

Revision ID: 3a5c60b49f2f
Revises: 5dd689a49084
Create Date: 2026-08-10 22:32:44.568994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a5c60b49f2f'
down_revision: Union[str, Sequence[str], None] = '5dd689a49084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('panel_ratio', sa.Float(), nullable=True),
    sa.Column('panel_max_ratio', sa.Float(), nullable=True),
    sa.Column('panel_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('panel_opacity', sa.Float(), nullable=True),
    sa.Column('text_font_size_px', sa.Integer(), nullable=True),
    sa.Column('text_line_height_ratio', sa.Float(), nullable=True),
    sa.Column('text_align', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text_padding_left_px', sa.Integer(), nullable=True),
    sa.Column('text_padding_right_px', sa.Integer(), nullable=True),
    sa.Column('text_padding_top_px', sa.Integer(), nullable=True),
    sa.Column('text_padding_bottom_px', sa.Integer(), nullable=True),
    sa.Column('highlight_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('watermark_max_px', sa.Integer(), nullable=True),
    sa.Column('watermark_top_ratio', sa.Float(), nullable=True),
    sa.Column('portrait_size_px', sa.Integer(), nullable=True),
    sa.Column('portrait_min_px', sa.Integer(), nullable=True),
    sa.Column('portrait_max_width_ratio', sa.Float(), nullable=True),
    sa.Column('portrait_ring_pad_px', sa.Integer(), nullable=True),
    sa.Column('portrait_border_width_px', sa.Integer(), nullable=True),
    sa.Column('portrait_border_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_layout_page_id'), 'page_layout', ['page_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_layout_page_id'), table_name='page_layout')
    op.drop_table('page_layout')
    # ### end Alembic commands ###
