"""page_layout.text_uppercase: draw the panel in capitals

Revision ID: 517b138512ff
Revises: 85d4da17f9d6
Create Date: 2026-08-15 18:54:42.119791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '517b138512ff'
down_revision: Union[str, Sequence[str], None] = '85d4da17f9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    As autogenerate wrote it, and nullable is the point rather than an
    oversight: every column on `page_layout` is three-valued. `NULL` is a Page
    that has not decided and still tracks `config/layout.yml`; `false` is a Page
    that has decided against capitals and will not follow the file if the file
    changes. Backfilling `false` would erase that difference on every existing
    row — which is the mistake `20974f89ec28` was adjusted to avoid on a column
    that genuinely could not be null.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_layout', sa.Column('text_uppercase', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_layout', 'text_uppercase')
    # ### end Alembic commands ###
