"""page_competitor: which competitors feed which pages

Adds the assignment table and the join key it needs on `source_item`.

**Seeds nothing, on purpose.** Every Page starts with zero assignments, and
`routes/sources._visible_to` falls back to provenance — the Metricool set a Page
owns — while that is true. So this revision changes no grid: the app behaves
exactly as before until someone assigns a competitor, and the first assignment
switches that Page over.

Seeding assignments from each Page's current Metricool set was the obvious
alternative and was rejected. It would need a vendor call from inside a
migration — credentials, network, and a 502 that leaves the schema half-applied
— to reproduce a state the fallback already provides for free.

`source_item.competitor_page_id` is left null on existing rows for the same
reason: it is populated from the sync, and a Refresh on the Competitors tab
fills it in. Until then those rows are only reachable through the fallback,
which is the path they were already on.

Revision ID: 5dd689a49084
Revises: 103581b4d2f1
Create Date: 2026-08-10 18:54:42.522452

"""
from typing import Sequence, Union

import sqlalchemy as sa

# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5dd689a49084'
down_revision: Union[str, Sequence[str], None] = '103581b4d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('competitor_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'competitor_page_id', name='uq_page_competitor_page_provider')
    )
    op.create_index(op.f('ix_page_competitor_competitor_page_id'), 'page_competitor', ['competitor_page_id'], unique=False)
    op.create_index(op.f('ix_page_competitor_page_id'), 'page_competitor', ['page_id'], unique=False)
    op.add_column('source_item', sa.Column('competitor_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_source_item_competitor_page_id'), 'source_item', ['competitor_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_item_competitor_page_id'), table_name='source_item')
    op.drop_column('source_item', 'competitor_page_id')
    op.drop_index(op.f('ix_page_competitor_page_id'), table_name='page_competitor')
    op.drop_index(op.f('ix_page_competitor_competitor_page_id'), table_name='page_competitor')
    op.drop_table('page_competitor')
    # ### end Alembic commands ###
