"""youtube tool: cta_template, youtube_job

The two tables the Shorts pipeline owns. Written by hand rather than
autogenerated: the live database is the only Postgres and there is no throwaway
one to diff against (docker is not available for migrations here), and the
shape is small enough to write correctly.

Enum columns are `VARCHAR` with the enum's values as Python, exactly the
`_stored_enum` convention in models.py: native Postgres enums would need an
`ALTER TYPE` for every new member, and a new status is a fact about the Python
class, not a schema change. This is also what keeps SQLite and Postgres
building the same schema, which is what the test suite relies on.

`youtube_job` is the queue: one row per video, claimed by the in-process worker
in `app/youtube/process.py`. The
`youtube_short_id`/`shorts_rank`/`view_count_snapshot` snapshot columns keep a
row readable after a channel's ranking shifts.

**No `youtube_schedule` here.** An earlier draft of this revision created one
and it still exists in the live database, empty and unreferenced — the rebuild
stops at "produce a video", and nothing distributes to Metricool yet. Whoever
builds that ships the table with the model, in its own revision, and drops the
orphan. Until then `alembic check` reports it as a removed table; that is this
paragraph, not a missing migration.

Revision ID: 77c12e0f0a01
Revises: e232c1fcb279
Create Date: 2026-08-19

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "77c12e0f0a01"
down_revision: Union[str, None] = "e232c1fcb279"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "cta_template",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("cta_video_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    op.create_table(
        "youtube_job",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("youtube_url", sa.String(), nullable=True),
        sa.Column("ingest_type", sa.String(), nullable=False, server_default=sa.text("'youtube'")),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("youtube_short_id", sa.String(), nullable=True),
        sa.Column("resolved_short_url", sa.String(), nullable=True),
        sa.Column("channel_shorts_url", sa.String(), nullable=True),
        sa.Column("shorts_rank", sa.Integer(), nullable=True),
        sa.Column("view_count_snapshot", sa.Integer(), nullable=True),
        sa.Column("like_count_snapshot", sa.Integer(), nullable=True),
        sa.Column("raw_title", sa.String(), nullable=True),
        sa.Column("trim_duration", sa.Integer(), nullable=False, server_default=sa.text("3")),
        sa.Column("cta_template_id", sa.Integer(), sa.ForeignKey("cta_template.id"), nullable=False),
        # VARCHAR enums, per _stored_enum — see head of file.
        sa.Column("status", sa.String(length=32), nullable=False, server_default=sa.text("'queued'")),
        sa.Column("progress", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("processed_video_path", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_youtube_job_cta_template_id", "youtube_job", ["cta_template_id"])
    op.create_index("ix_youtube_job_status", "youtube_job", ["status"])


def downgrade() -> None:
    op.drop_table("youtube_job")
    op.drop_table("cta_template")