"""saved_post: a published post kept for reference

Revision ID: 85d4da17f9d6
Revises: 9a8d2213232a
Create Date: 2026-08-12 13:10:17.679216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85d4da17f9d6'
down_revision: Union[str, Sequence[str], None] = '9a8d2213232a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('metricool_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permalink_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'metricool_post_id', name='uq_saved_post_page_post')
    )
    op.create_index(op.f('ix_saved_post_draft_id'), 'saved_post', ['draft_id'], unique=False)
    op.create_index(op.f('ix_saved_post_metricool_post_id'), 'saved_post', ['metricool_post_id'], unique=False)
    op.create_index(op.f('ix_saved_post_page_id'), 'saved_post', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_post_page_id'), table_name='saved_post')
    op.drop_index(op.f('ix_saved_post_metricool_post_id'), table_name='saved_post')
    op.drop_index(op.f('ix_saved_post_draft_id'), table_name='saved_post')
    op.drop_table('saved_post')
    # ### end Alembic commands ###
