"""draft template and no_image: per-draft card form, and text-only posts

Revision ID: 9a8d2213232a
Revises: e95cf1ff6545
Create Date: 2026-08-12 01:51:14.414186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a8d2213232a'
down_revision: Union[str, Sequence[str], None] = 'e95cf1ff6545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "draft",
        sa.Column("template", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # Adjusted from autogenerate, which wrote this as a bare `nullable=False`
    # with no default — the same trap `20974f89ec28` documents. Postgres cannot
    # add a NOT NULL column with no default to a table that already has rows,
    # and it fails at deploy rather than here.
    #
    # The default backfills every existing draft to `false`, which is correct:
    # each of them was generated with a picture. It is dropped immediately after
    # so the default does not live in two places and drift from the Python one.
    op.add_column(
        "draft",
        sa.Column("no_image", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("draft", "no_image", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'no_image')
    op.drop_column('draft', 'template')
    # ### end Alembic commands ###
