"""page watermark can be switched off

Revision ID: beada1f913db
Revises: 90c859b4e223
Create Date: 2026-08-11 02:04:13.021357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'beada1f913db'
down_revision: Union[str, Sequence[str], None] = '90c859b4e223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    `server_default` is the adjustment autogenerate asks for and does not make:
    it emitted a NOT NULL column with no default, which cannot be added to a
    table that already has ten rows — Postgres has nothing to put in them and
    the migration aborts. The default is the *existing* behaviour, so every Page
    keeps its mark and only a deliberate switch turns one off.

    It stays on the column rather than being dropped afterwards. The model's
    `default=True` covers rows this app inserts; the server default covers an
    INSERT that does not name the column, which is what `scripts/seed_page.py`
    and a psql session both do.
    """
    op.add_column(
        'page',
        sa.Column(
            'watermark_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'watermark_enabled')
    # ### end Alembic commands ###
