"""prompt_template page_id

Revision ID: d1ab74d861bc
Revises: a3f8c2d91b47
Create Date: 2026-09-10 15:46:19.455325

"""
from typing import Sequence, Union

import sqlalchemy as sa

# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd1ab74d861bc'
down_revision: Union[str, Sequence[str], None] = 'a3f8c2d91b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_schedule_job_id'), table_name='youtube_schedule')
    op.drop_index(op.f('ix_youtube_schedule_scheduled_at'), table_name='youtube_schedule')
    op.drop_index(op.f('ix_youtube_schedule_status'), table_name='youtube_schedule')
    op.drop_table('youtube_schedule')
    op.drop_index(op.f('ix_shortlist_run_day'), table_name='shortlist_run')
    op.drop_index(op.f('ix_shortlist_run_page_id'), table_name='shortlist_run')
    op.drop_table('shortlist_run')
    op.drop_table('skipped_item')
    op.add_column('prompt_template', sa.Column('page_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prompt_template_page_id'), 'prompt_template', ['page_id'], unique=False)
    op.create_foreign_key(None, 'prompt_template', 'page', ['page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_template', type_='foreignkey')
    op.drop_index(op.f('ix_prompt_template_page_id'), table_name='prompt_template')
    op.drop_column('prompt_template', 'page_id')
    op.create_table('skipped_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skipped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skipped_item_pkey')),
    sa.UniqueConstraint('kind', 'external_id', name=op.f('uq_skipped_item'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('shortlist_run',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('built_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('considered', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name=op.f('shortlist_run_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shortlist_run_pkey')),
    sa.UniqueConstraint('page_id', 'day', name=op.f('uq_shortlist_run_page_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shortlist_run_page_id'), 'shortlist_run', ['page_id'], unique=False)
    op.create_index(op.f('ix_shortlist_run_day'), 'shortlist_run', ['day'], unique=False)
    op.create_table('youtube_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('video_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('metricool_post_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metricool_blog_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publish_via', sa.VARCHAR(), server_default=sa.text("'metricool'::character varying"), autoincrement=False, nullable=False),
    sa.Column('instagram_target', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['youtube_job.id'], name=op.f('youtube_schedule_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_schedule_pkey'))
    )
    op.create_index(op.f('ix_youtube_schedule_status'), 'youtube_schedule', ['status'], unique=False)
    op.create_index(op.f('ix_youtube_schedule_scheduled_at'), 'youtube_schedule', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_youtube_schedule_job_id'), 'youtube_schedule', ['job_id'], unique=False)
    # ### end Alembic commands ###
