"""page_time_slot: when a Page publishes

Revision ID: e95cf1ff6545
Revises: 20974f89ec28
Create Date: 2026-08-11 23:35:21.597968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's own column types (AutoString) are rendered into these files by
# autogenerate, so the import has to be here even when a revision does not use it.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e95cf1ff6545'
down_revision: Union[str, Sequence[str], None] = '20974f89ec28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_time_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('minute_of_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'minute_of_day', name='uq_time_slot_page_minute')
    )
    op.create_index(op.f('ix_page_time_slot_minute_of_day'), 'page_time_slot', ['minute_of_day'], unique=False)
    op.create_index(op.f('ix_page_time_slot_page_id'), 'page_time_slot', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_time_slot_page_id'), table_name='page_time_slot')
    op.drop_index(op.f('ix_page_time_slot_minute_of_day'), table_name='page_time_slot')
    op.drop_table('page_time_slot')
    # ### end Alembic commands ###
