"""Prompts live in `api/prompts/*.txt`, not in the database.

They are the product, and they are edited far more often than anything else
here. As database columns they were invisible to git, unreviewable, and they
drifted: in the old system all three configured pages stored the full
2350-character image prompt, of which **2030 characters were byte-identical**,
and those copies went stale — they still said "HERO PHOTO (~75% height)" and
"CIRCLE BRAND LOGO" while the code they were copied from had moved on to a
panel that grows and a logo at natural aspect ratio. History Retraced's stored
overlay prompt carries that same stale block a second time, at offset 903.

As files they diff, review and revert. One file per prompt:

    prompts/system.txt     writer voice and post structure
    prompts/overlay.txt    how to write the panel text and pick highlights
    prompts/image.txt      hero photography style, card layers, exclusions

Read on every call — they are ~5KB total, and editing a prompt should not
require a restart.

## Per-Page overrides

    prompts/pages/<slug>/system.txt    overrides prompts/system.txt for one Page
    prompts/pages/<slug>/overlay.txt
    prompts/pages/<slug>/image.txt

Present means used, absent means the file above is used. **Whole files, never
fragments**, which is the same conclusion the `image_rules.txt` merge reached
below: nobody could place the line between "the brand's taste" and "the card's
contract" correctly, so there is no shared half to append to.

This does not reopen the database question. The reason prompts left the database
was that a textarea let ten copies of one prompt drift invisibly, and the
measurement that proved it is in the paragraph above. A file per Page in git
diffs, reviews and reverts exactly like the file it overrides; what it does not
do is let a copy go stale without anyone seeing it.

The evidence that per-Page prose is genuinely needed came from the same place as
the evidence against columns. The old tool's Bodybuilding Tips row was **byte
for byte** History Retraced's prompt — all four columns, unedited since it was
seeded — while the client believed for six weeks that they had written their
own. Their drafts came out as history posts because they were generated by a
history page's prompt (`docs/feedback/2026-08-15/old-tool-prompts.md`).

The slug is `Page.name`, lowercased, non-alphanumerics collapsed to hyphens —
the convention `assets/watermarks/history-retraced-stacked.png` already uses.
Derived, not stored, so there is no column to fall out of step; the cost is that
renaming a Page silently returns it to the global prompts, which is why
`list_prompt_files` reports the directory it resolved and the Settings screen
shows it.

`image.txt` was two files until the split was measured against its own rule.
The claim was that hero *style* varies by page while the *card contract* does
not, so they should live apart — but 7 of the 19 lines in the shared half were
History Retraced's taste, not the card's geometry: historical reenactment,
period-accurate dress, no surreal metaphors, mid-shot at 40–60% of frame. The
old system proves those are not universal, because it sent that same block to
Hot Tub Timeout and to a Bible Focus page whose own style block asked for
reverent fine-art photography the shared rules then forbade. A boundary nobody
can place a line on correctly is not a boundary; it had already caused
photorealism, mid-shot and documentary to be stated twice. Merging changed no
bytes — the concatenation this function used to do is now the file.

## Placeholders

A few numbers appear in both a prompt and the compositor, so they are written
as tokens and substituted from `layout.yml`. The old system hardcoded them and
they disagreed in production: History Retraced rendered a 20% panel while its
prompt told the model 25%, because the hint was built from a shared default
constant instead of the page's own value.

Substitution is a plain `str.replace`, not `str.format`, so a stray brace in a
prompt cannot raise at generation time.
"""

import re

from app.settings import API_DIR, Layout

PROMPTS_DIR = API_DIR / "prompts"
PAGES_DIR = PROMPTS_DIR / "pages"


def slug(page_name: str) -> str:
    """`Bodybuilding Tips N Tricks` -> `bodybuilding-tips-n-tricks`.

    Matches the watermark filenames, which were named by hand to this shape
    before there was a function for it.
    """
    return re.sub(r"[^a-z0-9]+", "-", page_name.lower()).strip("-")


def _tokens(layout: Layout) -> dict[str, str]:
    return {
        "{panel_pct}": str(round(layout.panel.ratio * 100)),
        "{highlight_color}": layout.highlight.color,
    }


def source_of(name: str, page_name: str | None = None):
    """The file that would be read for `name`, per Page or global.

    Split out from `_read` because two callers need the *path* and not the text:
    the Settings screen, which has to show which file the model is actually
    sent, and the test that asserts a Page with no directory falls back rather
    than raising.
    """
    if page_name:
        candidate = PAGES_DIR / slug(page_name) / name
        if candidate.is_file():
            return candidate
    return PROMPTS_DIR / name


COLUMN = {
    "system.txt": "system_prompt",
    "overlay.txt": "overlay_prompt",
    "image.txt": "image_prompt",
}
"""Which `Page` column overrides which file, for the three known prompts.

A prompt with no column here can only be a file. That is deliberate: the column
exists to be edited from the Settings screen, and a prompt nothing edits does
not need a second place to live.
"""


def stored(name: str, page) -> str | None:
    """This Page's own text for `name`, if someone has written one.

    Blank is not an override. A textarea that has been emptied means "go back to
    the inherited prompt", and storing `""` would instead send the model nothing
    at all — a Page with no voice, failing in a way that looks like the model
    misbehaving rather than like a setting.
    """
    if page is None:
        return None
    text = (getattr(page, COLUMN.get(name, ""), None) or "").strip()
    return text or None


def _read(
    name: str, layout: Layout, page_name: str | None = None, page=None
) -> str:
    """The text the model is sent: the Page's own, else the file for it.

    `page` is optional so the writer's own tests, and any caller that only has a
    name, keep working against files alone.
    """
    text = stored(name, page)
    if text is None:
        text = source_of(name, page_name).read_text(encoding="utf-8").strip()
    for token, value in _tokens(layout).items():
        text = text.replace(token, value)
    return text


def system_prompt(layout: Layout, page_name: str | None = None, page=None) -> str:
    return _read("system.txt", layout, page_name, page)


def overlay_prompt(layout: Layout, page_name: str | None = None, page=None) -> str:
    return _read("overlay.txt", layout, page_name, page)


def image_prompt(layout: Layout, page_name: str | None = None, page=None) -> str:
    return _read("image.txt", layout, page_name, page)


ORDER = ("system.txt", "overlay.txt", "image.txt")
"""Reading order, which is also the order the run uses them in."""


def list_prompt_files(
    layout: Layout, page_name: str | None = None, page=None
) -> list[dict]:
    """Every prompt file, for the Settings screen.

    Returns the text **as substituted**, not as typed, because what the operator
    needs to confirm is that the prompt agrees with `layout.yml` — a raw
    `{panel_pct}` on screen proves nothing. The file itself is still where edits
    happen; this is a read-only window onto what the model is actually told.

    Read from disk on every call, deliberately. The screen used to render a
    hardcoded copy of these bodies, and the copy drifted: it went on listing
    `image_rules.txt` after that file was merged into `image.txt`.

    `page_name` resolves the per-Page overrides, and each entry carries
    `overridden` saying whether it did. Without that flag the screen shows a
    History Retraced prompt while a Page with its own file is sent something
    else — the exact failure this window exists to catch, and the one the old
    tool shipped for six weeks.
    """
    found = {path.name: path for path in PROMPTS_DIR.glob("*.txt")}
    # Known files first, then anything else on disk, so a new prompt cannot be
    # added and go unnoticed here.
    names = [n for n in ORDER if n in found] + sorted(set(found) - set(ORDER))

    files = []
    for name in names:
        body = _read(name, layout, page_name, page)
        from_db = stored(name, page) is not None
        files.append(
            {
                "filename": name,
                "chars": len(body),
                "body": body,
                "overridden": from_db
                or source_of(name, page_name).parent != PROMPTS_DIR,
                # Which of the three places this text came from. The screen has
                # to say it plainly: an operator editing a prompt that is in
                # fact inherited is about to create an override they did not
                # ask for, and one editing a file-backed override on Railway
                # would lose it on the next redeploy.
                "source": (
                    "page"
                    if from_db
                    else (
                        "file-override"
                        if source_of(name, page_name).parent != PROMPTS_DIR
                        else "global"
                    )
                ),
                "editable": name in COLUMN,
            }
        )
    return files


def list_prompt_files_for(layout: Layout, page) -> list[dict]:
    """`list_prompt_files` for a Page row, which is what every caller now has."""
    return list_prompt_files(layout, page.name if page else None, page)
